spring.application.name=SamMasterProject
spring.security.username=sam
spring.security.password=admin
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration